import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'

const nunio = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="fr"
      className={`${nunio.variable} antialiased font-nunito`}
    >
      <body className="bg-linear-to-br from-indigo-50 via-white to-blue-50 text-gray-900">
        {children}
      </body>
    </html>
  )
}
